apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: magenta-production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: scheduler
      containers:
        - name: scheduler
          env:
            - name: MAGENTA_ENV
              value: "production"
            - name: MAGENTA_LOG_LEVEL
              value: "WARN"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
