apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: magenta-production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: worker
      containers:
        - name: worker
          env:
            - name: MAGENTA_ENV
              value: "production"
            - name: MAGENTA_LOG_LEVEL
              value: "WARN"
            - name: MAGENTA_WORKER__CONCURRENCY
              value: "10"
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
