extends: default

rules:
  line-length:
    max: 140
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: false
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
