apiVersion: v1
kind: Namespace
metadata:
  name: magenta-soa
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: magenta-agents
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: magenta-finops
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: magenta-mesh
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    istio-injection: enabled