apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: magenta-staging
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: collector
          env:
            - name: MAGENTA_ENV
              value: "staging"
            - name: MAGENTA_LOG_LEVEL
              value: "INFO"
            - name: MAGENTA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: magenta-secrets
                  key: api-key
            - name: MAGENTA_REDIS_PERSISTENCE
              value: "true"
          resources:
            requests:
              cpu: "300m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
