apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: magenta-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web-gateway
          env:
            - name: MAGENTA_ENV
              value: "staging"
            - name: MAGENTA_LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
