apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: magenta-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: worker
          env:
            - name: MAGENTA_ENV
              value: "staging"
            - name: MAGENTA_LOG_LEVEL
              value: "INFO"
            - name: MAGENTA_WORKER__CONCURRENCY
              value: "5"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
