apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-bridge
  namespace: magenta-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mcp-bridge
          env:
            - name: MAGENTA_ENV
              value: "dev"
            - name: MAGENTA_LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
